ARG PY_VERSION=3.10

FROM python:${PY_VERSION}-slim-bullseye as plugin-build

RUN apt-get update \
    && apt-get install -y git \
    && git clone --depth=1 -b 2.x https://github.com/ratanakvlun/deluge-ltconfig /ltconfig \
    && cd /ltconfig \
    && python setup.py bdist_egg


FROM python:${PY_VERSION}-slim-bullseye
ARG VERSION

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      geoip-database \
    && apt-get dist-upgrade -y \
    && pip3 install --no-cache-dir "deluge==${VERSION}" libtorrent \
    && useradd -m -u 1000 deluge \
    && apt-get auto-remove -y \
    && apt-get clean

# FIXME: Variables can't be used here as it seems...
COPY --from=plugin-build /ltconfig/dist/*.egg /usr/local/lib/python3.10/site-packages/deluge/plugins/
COPY files/core.conf /defaults/core.conf

ENV PYTHON_EGG_CACHE=/home/deluge/.cache
ENV SSL_CERT_DIR=/etc/ssl/certs

EXPOSE 8112 58846 58946 58946/udp
VOLUME /config
USER 1000

# Deluge Daemon:
CMD [ "/usr/local/bin/deluged", "-c", "/config", "-d"]
## Webserver:
#CMD [ "/usr/local/bin/deluge-web", "-d", "-c", "/config"]
