FROM alpine:edge

RUN apk update \
    && apk upgrade \
    && apk add squid \
    && rm -rf /var/cache/apk/* \
    && chown squid:squid /var/run

USER squid

CMD ["sh", "-c", "(tail -F /var/log/squid/access.log &) && /usr/sbin/squid -f /etc/squid/squid.conf -NYCd 1"]
