FROM lib42/base:bookwork-slim

ARG TARGETPLATFORM="linux/amd64"
ARG VERSION

ENV XDG_CONFIG_HOME=/config
USER root

# hadolint ignore=DL3008,DL3015,SC2039,SC2086
RUN \
    apt-get -qq update \
    && \
    apt-get -qq install -y \
        libicu72 \
    && \
    case "${TARGETPLATFORM}" in \
        'linux/amd64') export ARCH='AMDx64' ;; \
        'linux/arm64') export ARCH='ARM64' ;; \
    esac \
    && \
    mkdir /app /config \
    && \
    curl -fsSL "https://github.com/Jackett/Jackett/releases/download/v${VERSION}/Jackett.Binaries.Linux${ARCH}.tar.gz" \
        | tar ixzf - -C /app --strip-components 1 \
    && \
    rm -rf \
        /app/JackettUpdater* \
    && \
    apt-get autoremove -y \
    && apt-get clean \
    && \
    rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/ \
    && chown -R app:app /app /config \
    && chmod -R 755 /app /config

USER app

LABEL org.opencontainers.image.source="https://github.com/Jackett/Jackett"

ENTRYPOINT [ "app/jackett", "--NoUpdates" ]
