---
matrix:
  include:
  - IMAGE: base
    VERSION: "bookworm-slim"
    TAGS: '[ "latest", "${VERSION}" ]'
    ARGS: '[]'
  - IMAGE: deluge
    VERSION: ""
    TAGS: '[ "2", "latest" ]'
    ARGS: '[]'
  - IMAGE: conreq
    VERSION: ""
    TAGS: '[ "latest" ]'
    ARGS: '[]'
  - IMAGE: squid
    VERSION: ""
    TAGS: '[ "latest" ]'
    ARGS: '[]'
  - IMAGE: jackett
    # renovate: datasource=github-releases depName=Jackett/Jackett versioning=loose
    VERSION: 0.20.3444
    TAGS: '[ "latest", "${VERSION}" ]'
    ARGS: '[ "VERSION=${VERSION}" ]'

when:
  path:
    include:
      - .woodpecker/*
      - containers/${IMAGE}/**
  branch: main
  event: [ cron, manual, push, tag ]


pipeline:
  build:
    image: plugins/kaniko:1.6
    group: build
    settings:
      repo: lib42/${IMAGE}
      dockerfile: containers/${IMAGE}/Containerfile
      build_args: ${ARGS}
      expand_tag: true
      custom_labels:
        - org.opencontainers.image.url=${CI_REPO_LINK}
        - org.opencontainers.image.revision=${CI_COMMIT_SHA}
        - org.opencontainers.image.vendor=lib42
        - org.opencontainers.image.created=${CI_PIPELINE_CREATED}
      context: containers/${IMAGE}
      tags: ${TAGS}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
    - path:
      include:
        - .woodpecker/*
        - containers/${IMAGE}/**
      branch: main
      event: [ cron, manual, push, tag ]

  scan:
    image: "aquasec/trivy:latest"
    commands:
      - >
        trivy image -s HIGH,CRITICAL --ignore-unfixed --no-progress lib42/${IMAGE}:${VERSION}
    when:
      - path:
          include:
            - .woodpecker/*
            - containers/${IMAGE}/**
        branch: main
        event: [ cron, manual, push, tag ]
