---
matrix:
  include:
  - IMAGE: deluge
    TAGS: '[ "2.1.1", "latest" ]'
    ARGS: '[]'
  - IMAGE: conreq
    TAGS: '[ "latest" ]'
    ARGS: '[]'
  - IMAGE: squid
    TAGS: '[ "latest" ]'
    ARGS: '[]'

pipeline:
  build:
    image: plugins/kaniko:1.6
    settings:
      repo: lib42/${IMAGE}
      dockerfile: ${IMAGE}/Containerfile
      build_args: ${ARGS}
      expand_tag: true
      custom_labels:
        - org.opencontainers.image.url=${CI_REPO_LINK}
        - org.opencontainers.image.revision=${CI_COMMIT_SHA}
        - org.opencontainers.image.vendor=lib42
        - org.opencontainers.image.created=${CI_PIPELINE_CREATED}
      context: ${IMAGE}
      tags: ${TAGS}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      - path:
          include:
            - .woodpecker/*
            - ${IMAGE}/
        branch: main
      - event: [ cron, manual ]

  scan:
    image: "aquasec/trivy:latest"
    commands:
      - >
        trivy image -s HIGH,CRITICAL --ignore-unfixed --no-progress lib42/${IMAGE}:${VERSION}
    when:
      - path:
          include:
            - .woodpecker/*
            - ${IMAGE}/
        branch: main
      - event: [ cron, manual ]
